# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/aspectify',
                'doc_host': 'https://ruescog.github.io',
                'git_url': 'https://github.com/ruescog/aspectify',
                'lib_path': 'aspectify'},
  'syms': {'aspectify.core': {'aspectify.core.foo': ('core.html#foo', 'aspectify/core.py')}}}
