# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/aspectify',
                'doc_host': 'https://ruescog.github.io',
                'git_url': 'https://github.com/ruescog/aspectify',
                'lib_path': 'aspectify'},
  'syms': { 'aspectify.aop': { 'aspectify.aop.Aspect': ('aop.html#aspect', 'aspectify/aop.py'),
                               'aspectify.aop.Aspect.__init__': ('aop.html#aspect.__init__', 'aspectify/aop.py'),
                               'aspectify.aop.Aspect.create_pointcut': ('aop.html#aspect.create_pointcut', 'aspectify/aop.py'),
                               'aspectify.aop.Aspect.set_after': ('aop.html#aspect.set_after', 'aspectify/aop.py'),
                               'aspectify.aop.Aspect.set_after_returning': ('aop.html#aspect.set_after_returning', 'aspectify/aop.py'),
                               'aspectify.aop.Aspect.set_after_throwing': ('aop.html#aspect.set_after_throwing', 'aspectify/aop.py'),
                               'aspectify.aop.Aspect.set_around': ('aop.html#aspect.set_around', 'aspectify/aop.py'),
                               'aspectify.aop.Aspect.set_before': ('aop.html#aspect.set_before', 'aspectify/aop.py'),
                               'aspectify.aop.advice': ('aop.html#advice', 'aspectify/aop.py'),
                               'aspectify.aop.is_detectable': ('aop.html#is_detectable', 'aspectify/aop.py')},
            'aspectify.examples': {},
            'aspectify.examples2': {}}}
